version: '3.8'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - /var/www/html/node_modules
    depends_on:
      - mysql
    networks:
      - centaurion-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: fhw8phnv2p
      MYSQL_DATABASE: centaurion_db
      MYSQL_USER: aver
      MYSQL_PASSWORD: fhw8phnv2p
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - centaurion-network

networks:
  centaurion-network:
    driver: bridge

volumes:
  mysql_data: 